In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import plot_tree
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import joblib

In [2]:
df =  pd.read_csv("loan_prediction_dataset.csv")

In [3]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
df.drop('Loan_ID',axis=1,inplace=True)

In [7]:
df.drop('Property_Area',axis=1,inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             601 non-null    object
 1   Married            611 non-null    object
 2   Dependents         599 non-null    object
 3   Education          614 non-null    object
 4   Self_Employed      582 non-null    object
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(6)
memory usage: 52.9+ KB

In [11]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [12]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Loan_Status           0
dtype: int64

In [14]:
categorical_cols = [
    "Gender",
    "Married",
    "Dependents",
    "Self_Employed",
    "Credit_History",
    "Loan_Amount_Term"
]

for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df["LoanAmount"].fillna(df["LoanAmount"].median(), inplace=True)

df.isnull().sum()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15324\2353648559.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15324\2353648559.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["LoanAmount"].fillna(df["LoanAmount"].median(), inplace=True)

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Loan_Status          0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
#encoding of categorical feature
le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col])

df.head(10)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status
0,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,1
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,1
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,1
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,1
5,1,1,2,0,1,5417,4196.0,267.0,360.0,1.0,1
6,1,1,0,1,0,2333,1516.0,95.0,360.0,1.0,1
7,1,1,3,0,0,3036,2504.0,158.0,360.0,0.0,0
8,1,1,2,0,0,4006,1526.0,168.0,360.0,1.0,1
9,1,1,1,0,0,12841,10968.0,349.0,360.0,1.0,0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    int64
 1   Married            614 non-null    int64
 2   Dependents         614 non-null    int64
 3   Education          614 non-null    int64
 4   Self_Employed      614 non-null    int64
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Loan_Status        614 non-null    int64
dtypes: float64(4), int64(7)
memory usage: 52.9 KB

In [21]:
corr = df.corr(numeric_only=True)
print(corr)

                     Gender   Married  Dependents  Education  Self_Employed  \
Gender             1.000000  0.364569    0.172914   0.045364      -0.000525
Married            0.364569  1.000000    0.334216   0.012304       0.004489
Dependents         0.172914  0.334216    1.000000   0.055752       0.056798
Education          0.045364  0.012304    0.055752   1.000000      -0.010383
Self_Employed     -0.000525  0.004489    0.056798  -0.010383       1.000000
ApplicantIncome    0.058809  0.051708    0.118202  -0.140760       0.127180
CoapplicantIncome  0.082912  0.075948    0.030430  -0.062290      -0.016100
LoanAmount         0.106904  0.146546    0.163103  -0.168759       0.115100
Loan_Amount_Term  -0.074030 -0.100912   -0.103864  -0.073928      -0.033739
Credit_History     0.009170  0.010938   -0.040160  -0.073658      -0.001550
Loan_Status        0.017987  0.091478    0.010118  -0.085884      -0.003700

                   ApplicantIncome  CoapplicantIncome  LoanAmount  \
Gender                    0.058809           0.082912    0.106904
Married                   0.051708           0.075948    0.146546
Dependents                0.118202           0.030430    0.163103
Education                -0.140760          -0.062290   -0.168759
Self_Employed             0.127180          -0.016100    0.115100
ApplicantIncome           1.000000          -0.116605    0.565181
CoapplicantIncome        -0.116605           1.000000    0.189218
LoanAmount                0.565181           0.189218    1.000000
Loan_Amount_Term         -0.046531          -0.059383    0.036960
Credit_History           -0.018615           0.011134   -0.000607
Loan_Status              -0.004710          -0.059187   -0.033214

                   Loan_Amount_Term  Credit_History  Loan_Status
Gender                    -0.074030        0.009170     0.017987
Married                   -0.100912        0.010938     0.091478
Dependents                -0.103864       -0.040160     0.010118
Education                 -0.073928       -0.073658    -0.085884
Self_Employed             -0.033739       -0.001550    -0.003700
ApplicantIncome           -0.046531       -0.018615    -0.004710
CoapplicantIncome         -0.059383        0.011134    -0.059187
LoanAmount                 0.036960       -0.000607    -0.033214
Loan_Amount_Term           1.000000       -0.004705    -0.022549
Credit_History            -0.004705        1.000000     0.540556
Loan_Status               -0.022549        0.540556     1.000000

In [22]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
model = DecisionTreeClassifier( criterion="gini",
    random_state=42)
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [28]:
y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "actual":y_test,
    "predicted": y_pred
})

comparison.head(10)

     actual  predicted
350       1          0
377       1          0
163       1          1
609       1          1
132       1          1
578       1          1
316       1          1
2         1          1
340       0          0
77        0          0

In [29]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.7398373983739838

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.62      0.65      0.64        43
           1       0.81      0.79      0.80        80

    accuracy                           0.74       123
   macro avg       0.71      0.72      0.72       123
weighted avg       0.74      0.74      0.74       123

In [31]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})


print(importance)

             Feature  Importance
0             Gender    0.039344
1            Married    0.006124
2         Dependents    0.048054
3          Education    0.002117
4      Self_Employed    0.015791
5    ApplicantIncome    0.263341
6  CoapplicantIncome    0.101438
7         LoanAmount    0.195224
8   Loan_Amount_Term    0.035075
9     Credit_History    0.293493

In [33]:
joblib.dump(model, "loan_prediction_model.pkl")

['loan_prediction_model.pkl']